CREATE DATABASE OrderDb;
GO

USE OrderDb;

CREATE TABLE Orders (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    ExternalOrderId NVARCHAR(100) NOT NULL UNIQUE,
    Status INT NOT NULL,
    CreatedAt DATETIME2 NOT NULL
);

CREATE TABLE OrderItems (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    OrderId UNIQUEIDENTIFIER NOT NULL,
    ProductName NVARCHAR(100) NOT NULL,
    Quantity INT NOT NULL,
    UnitPrice DECIMAL(18,2) NOT NULL,
    FOREIGN KEY (OrderId) REFERENCES Orders(Id)
);